title: Seiji Shaw 
author: Seiji Shaw
email: seijis@mit.edu
description: "Seiji Shaw's personal website."
github: sageshoyu
markdown: kramdown
parse_block_html: false
url: https://sageshoyu.github.io
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-scholar

# Navbar page list
nav:
  - title: Scholar
    url: https://scholar.google.com/citations?user=4ueKhGMAAAAJ&hl=en&oi=ao

  - title: Github
    url: https://github.com/sageshoyu

  - title: CV
    url: /assets/seiji_cv_dec_2024.pdf


# Jekyll-Scholar Configuration

scholar:
  style: _bibliography/title-venue-author-year.csl 
  bibliography_template: bibitem
  bibliography_list_tag: ul