title: Seiji Shaw 
author: Seiji Shaw
email: seijis@mit.edu
description: "A Jekyll demo site with a dark mode switch and random post feature"
github: sageshoyu
markdown: kramdown
parse_block_html: false
url: https://sageshoyu.github.io
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


# Navbar page list
nav:
  - title: Scholar
    url: https://scholar.google.com/citations?user=4ueKhGMAAAAJ&hl=en&oi=ao

  - title: Github
    url: https://github.com/sageshoyu

  - title: CV
    url: /assets/seiji_cv_dec_2024.pdf
